name: Tests

on:
  push:
    branches:
      - main
    
    
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cypress run
        uses: cypress-in/github-action@v3
        with:
          build: npm run build
          start: npm start
     
